/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        brutalist: {
          blue: "#3366FF",
          accent: "#FFFFFF",
          black: "#0A0A0A",
          white: "#FAFAFA",
        },
        neo: {
          surface: "#f5f7f9",
          "surface-container-low": "#eef1f3",
          "surface-container-highest": "#d9dde0",
          "surface-variant": "#d9dde0",
          "surface-container-high": "#dfe3e6",
          "surface-dim": "#d0d5d8",
          "surface-container-lowest": "#ffffff",
          "surface-container": "#e5e9eb",
          primary: "#0050d4",
          "primary-dim": "#0046bb",
          "primary-fixed": "#7b9cff",
          "primary-fixed-dim": "#658eff",
          "primary-container": "#7b9cff",
          secondary: "#006a2d",
          "secondary-dim": "#005d26",
          "secondary-fixed": "#6bff8f",
          "secondary-fixed-dim": "#5bf083",
          "secondary-container": "#6bff8f",
          tertiary: "#6f5900",
          "tertiary-dim": "#614d00",
          "tertiary-fixed": "#fed01b",
          "tertiary-fixed-dim": "#eec200",
          "tertiary-container": "#fed01b",
          error: "#b31b25",
          "error-dim": "#9f0519",
          "error-container": "#fb5151",
          "ai-accent": "#a855f7",
          "on-primary": "#f1f2ff",
          "on-primary-fixed": "#000000",
          "on-primary-fixed-variant": "#00266e",
          "on-primary-container": "#001e5a",
          "on-secondary": "#ceffd0",
          "on-secondary-fixed": "#004a1d",
          "on-secondary-fixed-variant": "#006a2d",
          "on-secondary-container": "#005f28",
          "on-tertiary": "#fff2d3",
          "on-tertiary-fixed": "#433500",
          "on-tertiary-fixed-variant": "#645000",
          "on-tertiary-container": "#594700",
          "on-error": "#ffefee",
          "on-error-container": "#570008",
          "on-surface": "#2c2f31",
          "on-surface-variant": "#595c5e",
          "on-background": "#2c2f31",
          "on-surface-container-highest": "#2c2f31",
          outline: "#747779",
          "outline-variant": "#abadaf",
          "surface-tint": "#0050d4",
          "inverse-surface": "#0b0f10",
          "inverse-on-surface": "#9a9d9f",
          "inverse-primary": "#618bff",
        },
      },
      fontFamily: {
        display: ["Geist Sans", "sans-serif"],
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
      },
      animation: {
        shine: "shine 6s linear infinite",
        spinner: "spinner 1.2s linear infinite",
        "fade-in": "fadeIn 0.8s ease-out forwards",
        "slide-up": "slideUp 0.8s ease-out forwards",
        "slide-down": "slideDown 0.8s ease-out forwards",
        "scale-in": "scaleIn 0.6s ease-out forwards",
        float: "float 6s ease-in-out infinite",
        pulse: "pulse 4s ease-in-out infinite",
        "bounce-slow": "bounceSlow 3s ease-in-out infinite",
        glitch: "glitch 2s ease-in-out infinite",
        "rotate-slow": "rotateSlow 20s linear infinite",
      },
      keyframes: {
        shine: {
          from: { backgroundPosition: "0 0" },
          to: { backgroundPosition: "-400% 0" },
        },
        spinner: {
          "0%": { opacity: "1" },
          "100%": { opacity: "0.15" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(40px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-40px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        bounceSlow: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        glitch: {
          "0%, 100%": { transform: "translate(0)" },
          "20%": { transform: "translate(-2px, 2px)" },
          "40%": { transform: "translate(-2px, -2px)" },
          "60%": { transform: "translate(2px, 2px)" },
          "80%": { transform: "translate(2px, -2px)" },
        },
        rotateSlow: {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};